In [1]:
import numpy as np

# Task 1
vector_1 = np.array([1, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector_1)

[ 1  3  4  5  6  7  8  9 10]


In [6]:
# Task 2
mt = np.array([[0]*3]*3)
print(mt)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# Task 3
mt2 = np.random.randint(0, 10, (5, 5))
print(mt2)

[[5 0 5 5 1]
 [4 1 8 7 4]
 [1 8 0 6 1]
 [9 8 5 0 6]
 [6 5 1 0 9]]


In [13]:
# Task 4
mt3 = np.random.rand(4, 4)
print(mt3)

[[0.20705969 0.69070864 0.89861306 0.45530471]
 [0.20455715 0.29922572 0.25732835 0.23848023]
 [0.89806221 0.33455228 0.85277552 0.70124052]
 [0.0562441  0.16234419 0.08756811 0.09975092]]


In [37]:
# Task 5
arr_1 = np.random.randint([np.random.randint(1, 10)]*5)
arr_2 = np.random.randint([np.random.randint(1, 10)]*5)


In [40]:
print(arr_1, arr_2)
print(F"arr_1 + arr_2 = {arr_1 + arr_2}")
print(F"arr_1 - arr_2 = {arr_1 - arr_2}")
print(F"arr_1 * arr_2 = {arr_1 * arr_2}")

[1 1 2 0 3] [5 6 3 0 7]
arr_1 + arr_2 = [ 6  7  5  0 10]
arr_1 - arr_2 = [-4 -5 -1  0 -4]
arr_1 * arr_2 = [ 5  6  6  0 21]


In [42]:
# Task 6
vect_1 = np.random.randint([np.random.randint(5, 56)]*7)
vect_2 = np.random.randint([np.random.randint(15, 155)]*7)

In [43]:
print(f"скалярний добуток {vect_1} i {vect_2} = {np.dot(vect_1, vect_2)}")

скалярний добуток [25  2 38  2 36 19 10] i [29 70 99 52 96 78 93] = 10599


In [48]:
# Task 7
arr1 = np.random.randint(1, 10, (2, 2))
arr2 = np.random.randint(1, 10, (2, 3))

In [51]:
print(f"{arr1} * {arr2} = {np.dot(arr1, arr2)}")

[[9 8]
 [8 8]] * [[8 4 7]
 [1 1 5]] = [[ 80  44 103]
 [ 72  40  96]]


In [54]:
# Task 8
arr = np.random.randint(1, 10, (3, 3))

In [57]:
print(arr)
arr_inv = np.linalg.inv(arr)
print(f"Inv arr = {arr_inv}")

[[1 9 7]
 [2 2 7]
 [9 6 7]]
Inv arr = [[-0.0754717  -0.05660377  0.13207547]
 [ 0.13207547 -0.1509434   0.01886792]
 [-0.01617251  0.20215633 -0.04312668]]


In [58]:
# Task 9
arr = np.random.rand(4, 4)


In [60]:
print(arr)
print(f"Транспонована матриця:\n {arr.T}")

[[0.55816829 0.10782529 0.7213657  0.8667135 ]
 [0.5001594  0.88698853 0.79549973 0.90626301]
 [0.98044731 0.31913612 0.94656423 0.93396063]
 [0.72350875 0.29691404 0.34133638 0.64273306]]
Транспонована матриця:
 [[0.55816829 0.5001594  0.98044731 0.72350875]
 [0.10782529 0.88698853 0.31913612 0.29691404]
 [0.7213657  0.79549973 0.94656423 0.34133638]
 [0.8667135  0.90626301 0.93396063 0.64273306]]


In [70]:
# Task 10
arr = np.random.randint(1, 10, (3, 4))
vect = np.random.randint([np.random.randint(1, 10)]*4)


In [71]:
res = np.dot(arr, vect)
print(f"arr * vect = {res}")

arr * vect = [24 52 29]


In [83]:
# Task 11
arr = np.random.rand(3, 4)
vect = np.random.ranf(4)

In [89]:
res = np.dot(arr, vect)
print(f"arr * vect = {res}")

arr * vect = [1.26632801 1.42892483 0.85591447]


In [86]:
# Task 12
arr1 = np.random.randint(1, 10, (2, 2))
arr2 = np.random.randint(1, 10, (2, 2))

In [87]:
print(f"arr1 * arr2 = {arr1 * arr2}")

arr1 * arr2 = [[36 36]
 [45 42]]


In [90]:
# Task 13
arr1 = np.random.randint(1, 10, (2, 2))
arr2 = np.random.randint(1, 10, (2, 2))

In [91]:
res = np.dot(arr1, arr2)
print(res)

[[87 93]
 [67 89]]


In [94]:
# Task 14
arr = np.random.randint(1, 100, (5, 5))

In [96]:
print(arr)
print(arr.sum())

[[95 24 42 41 75]
 [67 27 24 88 94]
 [ 2 46 89 14 23]
 [35 91 24 66 11]
 [28 21 76 43 55]]
1201


In [97]:
# Task 15
arr1 = np.random.randint(1, 10, (4, 4))
arr2 = np.random.randint(1, 10, (4, 4))

In [98]:
print(arr1 - arr2)

[[ 4  1 -2  5]
 [ 6 -3  0  3]
 [ 1 -2 -7  3]
 [ 6 -5  0 -2]]


In [101]:
# Task 16
arr = np.random.rand(3, 3)

In [105]:
print(arr)
print(arr.sum(axis=1))

[[0.96146759 0.85626962 0.37037536]
 [0.94706656 0.70371681 0.39935142]
 [0.5122887  0.45976029 0.40393289]]
[2.18811257 2.05013479 1.37598187]


In [106]:
# Task 17
arr = np.random.randint(2, 64, (3, 4))

In [107]:
print(arr)
print(arr ** 0.5)

[[19 43 17 50]
 [12 59 44 40]
 [60 30 22 31]]
[[4.35889894 6.55743852 4.12310563 7.07106781]
 [3.46410162 7.68114575 6.63324958 6.32455532]
 [7.74596669 5.47722558 4.69041576 5.56776436]]


In [110]:
# Task 18
vect = np.random.randint([np.random.randint(1, 50)]*4)

In [111]:
print(vect)
print(np.sqrt(vect))

[20  5  5 18]
[4.47213595 2.23606798 2.23606798 4.24264069]
